FROM golang:latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

ARG PORT=3000
ARG GIN_MODE=release
ARG ALLOWED_ORIGINS=*.google.com
ARG REDIS_URI=redis://127.0.0.1:6379
ARG DATA_DB_HOST=postgres.cpamekq08d5l.ap-south-1.rds.amazonaws.com
ARG DATA_DB_USER=postgres
ARG DATA_DB_PASSWORD=postgres
ARG DATA_DB_PORT=5432
ARG YOUTUBE_API_KEY1=AIzaSyAErzvQWYUvz6oL7OAd606xYuZHK8Vd7PA
ARG YOUTUBE_API_KEY2=AIzaSyD5J9Q-1J9Q-1J9Q-1J9Q-1J9Q-1J9Q-1J9Q
ARG YOUTUBE_API_KEY3=AIzaSyD5J9Q-1J9Q-1J9Q-1J9Q-1J9Q-1J9Q-1J9Q

ENV PORT=$PORT
ENV GIN_MODE=$GIN_MODE
ENV ALLOWED_ORIGINS=$ALLOWED_ORIGINS
ENV REDIS_URI=$REDIS_URI
ENV DATA_DB_HOST=$DATA_DB_HOST
ENV DATA_DB_USER=$DATA_DB_USER
ENV DATA_DB_PASSWORD=$DATA_DB_PASSWORD
ENV DATA_DB_PORT=$DATA_DB_PORT
ENV YOUTUBE_API_KEY1=$YOUTUBE_API_KEY1
ENV YOUTUBE_API_KEY2=$YOUTUBE_API_KEY2
ENV YOUTUBE_API_KEY3=$YOUTUBE_API_KEY3

RUN go build -o main .

EXPOSE 3000

CMD ["./main"]
